# Generated by Django 4.2.2 on 2023-07-08 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surnames", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=9, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("yearBirth", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("nid", models.CharField(max_length=9, unique=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("descr", models.CharField(blank=True, max_length=255, null=True)),
                ("studies", models.CharField(blank=True, max_length=255, null=True)),
                ("xpYears", models.PositiveSmallIntegerField(default=0)),
                ("estHours", models.PositiveSmallIntegerField(default=0)),
                (
                    "academyEmail",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("subjects", models.CharField(blank=True, max_length=150, null=True)),
                ("bankAccount", models.CharField(blank=True, max_length=40, null=True)),
                ("bicSwift", models.CharField(blank=True, max_length=20, null=True)),
                ("extra", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=40, null=True)),
                ("active", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
