# Generated by Django 4.2.2 on 2023-07-16 20:06

from django.db import migrations
from ..data.subjects import subjects

def cleanDb(apps, schema_editor):
  """Reiniciado de la base de datos"""
  Subject = apps.get_model('mainApp', 'subject')
  Origin = apps.get_model('mainApp', 'origin')
  Subject.objects.all().delete()
  Origin.objects.all().delete()

def populateDb(apps, schema_editor):
  """Poblado de la base de datos"""
  Subject = apps.get_model('mainApp', 'subject')
  Origin = apps.get_model('mainApp', 'origin')

  Subject.objects.bulk_create(
    [ Subject(name = subject) for subject in subjects.split('\n') ]
  )
  Origin.objects.bulk_create(
    [ Origin(name = origin) for origin in origins.split('\n') ]
  )

class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
      migrations.RunPython(cleanDb),
      migrations.RunPython(populateDb),
    ]