# Generated by Django 4.2.2 on 2023-07-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_populate_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="availability",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mainApp.origin",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="prices",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
