# Generated by Django 4.2.2 on 2023-07-20 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_alter_client_options_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="administrator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
