# Generated by Django 4.2.2 on 2023-07-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_client_contract_client_descr_student_descr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="students",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mainApp.student",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="students",
            field=models.ManyToManyField(null=True, to="mainApp.student"),
        ),
    ]
