# Generated by Django 4.2.2 on 2023-07-18 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_populate_db"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="category",
            new_name="speciality",
        ),
    ]
