# Generated by Django 4.2.2 on 2023-07-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_populate_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="fullname",
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="nid",
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="nid",
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
