# Generated by Django 4.2.2 on 2023-07-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0003_alter_baseuser_fullname_alter_client_nid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="bank",
            new_name="bankName",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="bank",
            new_name="bankName",
        ),
        migrations.AlterField(
            model_name="teacher",
            name="availability",
            field=models.CharField(
                blank=True,
                default="Lunes: &#13;&#10;Martes: &#13;&#10;Miércoles: &#13;&#10;Jueves: &#13;&#10;Viernes: &#13;&#10;Sábado: &#13;&#10;Domingo: ",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="prices",
            field=models.CharField(
                blank=True,
                default="ESO: 16.6 € / h&#13;&#10;Bachiller: 18 € / h&#13;&#10;Universidad: 20 € / h&#13;&#10;Bachiller: 18 € / h&#13;&#10;Premium: 25 € / h",
                max_length=150,
                null=True,
            ),
        ),
    ]
