# Generated by Django 4.2.2 on 2023-07-18 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0003_rename_category_teacher_speciality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="xpYears",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="yearBirth",
        ),
    ]
