# Generated by Django 4.2.2 on 2023-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0003_teacher_admin_alter_teacher_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="category",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
