# Generated by Django 4.2.2 on 2023-07-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0004_remove_teacher_xpyears_remove_teacher_yearbirth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="nid",
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="nid",
            field=models.CharField(max_length=9),
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subjects",
        ),
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(blank=True, to="mainApp.subject"),
        ),
    ]
