# Generated by Django 4.2.2 on 2023-07-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0004_rename_bank_client_bankname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="availability",
            field=models.CharField(
                blank=True,
                default="Lunes: \nMartes: \nMiércoles: \nJueves: \nViernes: \nSábado: \nDomingo: ",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="prices",
            field=models.CharField(
                blank=True,
                default="ESO: 16.6 € / h\nBachiller: 18 € / h\nUniversidad: 20 € / h\nBachiller: 18 € / h\nPremium: 25 € / h",
                max_length=2000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="speciality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
