# Generated by Django 4.2.2 on 2023-07-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0005_alter_client_nid_alter_teacher_nid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="bank",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="dpLaw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="fullname",
            field=models.CharField(default="", max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="fullname",
            field=models.CharField(default="", max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="bank",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="dpLaw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="fullname",
            field=models.CharField(default=" ", max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="workingXp",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="client",
            name="nid",
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="surnames",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="surnames",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="nid",
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="surnames",
            field=models.CharField(max_length=60),
        ),
    ]
