# Generated by Django 4.2.2 on 2023-07-23 15:04

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0005_alter_teacher_availability_alter_teacher_prices_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="client",
            name="validated",
        ),
        migrations.AddField(
            model_name="student",
            name="availability",
            field=models.CharField(
                blank=True,
                default="Lunes: \nMartes: \nMiércoles: \nJueves: \nViernes: \nSábado: \nDomingo: ",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="eval",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="hourlyPrice",
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name="student",
            name="profilePic",
            field=models.ImageField(
                blank=True, null=True, upload_to=mainApp.models.Student.file_upload_to
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="subjects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mainApp.subject",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="weeklyHours",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="client",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mainApp.origin",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="contract",
            field=models.FileField(
                blank=True, null=True, upload_to=mainApp.models.Teacher.file_upload_to
            ),
        ),
    ]
